version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
    networks:
      - backendnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password1234@db:3306/DBSim
    networks:
      - backendnet

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: DBSim
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backendnet

volumes:
  db_data:

networks:
  backendnet:
