version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password123@db:3306/DBSim

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: DBSim
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
