name: Deploy React + Flask via Docker

on:
  push:
    branches: [ owen ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into Azure VM and deploy Docker containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            PROJECT_DIR="/home/${{ secrets.AZURE_VM_USERNAME }}/project-folder"

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              git clone https://github.com/${{ github.repository }} $PROJECT_DIR
            fi

            cd $PROJECT_DIR
            git pull origin owen

            docker-compose up -d --build
